name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main   # Se despliega solo al actualizar MAIN

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependencias
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # üîê LOGIN A AZURE USANDO SERVICE PRINCIPAL
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # üì¶ Crear ZIP con todo Laravel
      - name: Empaquetar la app
        run: zip -r app.zip .

      # üöÄ DEPLOY
      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ProyectoEquipo3"   # Nombre EXACTO del App Service en Azure
          package: app.zip
