name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main   # Solo se despliega cuando main recibe cambios

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar cÃ³digo del repo
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependencias
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # ðŸ”¥ðŸ”¥ IMPORTANTE: nombre EXACTO de tu App Service
      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ProyectoEquipo3"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

